apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app.kubernetes.io/name: hello
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hello
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080